"use client"

import { useState, useEffect, useRef } from "react"
import { useRouter, useSearchParams } from "next/navigation"
import {
  Shield,
  Sparkles,
  Wand2,
  Volume2,
  Copy,
  MessageSquare,
  ChevronDown,
  ChevronUp,
  Check,
  BrainCircuit,
  Mic,
  Loader2,
  FileText,
  SeparatorVertical as Separator,
  List,
  Plus,
  Trash2,
} from "lucide-react"
import { Input } from "@/components/ui/input"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { Textarea } from "@/components/ui/textarea"
import { Label } from "@/components/ui/label"
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group"
import Link from "next/link"
import { createClient } from "@/lib/supabase/client"

export default function CreateViralPage() {
  const router = useRouter()
  const searchParams = useSearchParams()

  // CORREÇÃO AQUI: Tratamento das strings "undefined" e "null"
  const rawAlert = searchParams.get("alert")
  const alertId = (rawAlert === "undefined" || rawAlert === "null") ? null : rawAlert

  const rawProposal = searchParams.get("proposal")
  const proposalId = (rawProposal === "undefined" || rawProposal === "null") ? null : rawProposal

  const source = searchParams.get("source")
  const originId = searchParams.get("originId")
  const contentType = "audio"
  const [alert, setAlert] = useState<any>(null)
  const [proposal, setProposal] = useState<any>(null)
  const [tone, setTone] = useState("urgent")
  const [targetAudience, setTargetAudience] = useState("geral")
  const [generatedScript, setGeneratedScript] = useState("")
  const [isGenerating, setIsGenerating] = useState(false)
  const [isSaving, setIsSaving] = useState(false)
  const [audioUrl, setAudioUrl] = useState<string | null>(null)
  const [isGeneratingAudio, setIsGeneratingAudio] = useState(false)
  const [hasAutoGenerated, setHasAutoGenerated] = useState(false)
  const [isTransmitting, setIsTransmitting] = useState(false)
  const [isSendingWhatsapp, setIsSendingWhatsapp] = useState(false)
  const [sendPoll, setSendPoll] = useState(true)
  const [pollQuestion, setPollQuestion] = useState("Qual sua opinião sobre isso?")
  const [pollOptions, setPollOptions] = useState<string[]>(["Concordo", "Discordo", "Neutro"])

  const audioRef = useRef<HTMLAudioElement | null>(null)
  const audioContainerRef = useRef<HTMLDivElement | null>(null)
  const audioUrlRef = useRef<string | null>(null)
  const [phoneNumber, setPhoneNumber] = useState("")
  const [channels, setChannels] = useState<any[]>([])
  const [isLoadingChannels, setIsLoadingChannels] = useState(false)
  const [groups, setGroups] = useState<any[]>([])
  const [isLoadingGroups, setIsLoadingGroups] = useState(false)
  const [isChannelsOpen, setIsChannelsOpen] = useState(false)
  const [isGroupsOpen, setIsGroupsOpen] = useState(false)
  const [selectedChannelName, setSelectedChannelName] = useState("")
  const [selectedGroupName, setSelectedGroupName] = useState("")

  useEffect(() => {
    return () => {
      if (audioUrlRef.current) {
        try {
          URL.revokeObjectURL(audioUrlRef.current)
        } catch { }
        audioUrlRef.current = null
      }
    }
  }, [])
  useEffect(() => {
    const loadData = async () => {
      // Prioridade 1: Carregar por Alert ID
      if (alertId) {
        await loadAlert()
        return
      }

      // Prioridade 2: Carregar por Proposal ID direto
      if (proposalId) {
        await loadProposal()
        return
      }

      // Prioridade 3: Carregar por Origem (seu caso atual)
      if (source === "analyze" && originId) {
        await loadProposalById(originId)
      }
    }

    loadData()
  }, [alertId, proposalId, source, originId]) // Dependências corretas

  const loadAlert = async () => {
    console.log("[v0] Loading alert with ID:", alertId)
    const supabase = createClient()
    const { data } = await supabase
      .from("risk_alerts")
      .select(`
        *,
        legislative_proposals (
          title,
          external_id
        )
      `)
      .eq("id", alertId)
      .single()

    console.log("[v0] Alert loaded:", data)
    if (data) {
      setAlert(data)
    }
  }

  const loadProposal = async () => {
    const supabase = createClient()
    const { data } = await supabase.from("legislative_proposals").select("*").eq("id", proposalId).single()

    if (data) {
      setProposal(data)
    }
  }

  const loadProposalById = async (id: string) => {
    const supabase = createClient()
    const { data } = await supabase.from("legislative_proposals").select("*").eq("id", id).single()
    if (data) setProposal(data)
  }

  const generateScript = async () => {
    if (isGenerating) return

    setIsGenerating(true)
    let analysisText = ""
    let title = ""

    try {
      if (!alert && !proposal) {
        if (source === "analyze" && originId) {
          await loadProposalById(originId)
        } else if (proposalId) {
          await loadProposal()
        }
      }

      if (!alert && !proposal) {
        setIsGenerating(false)
        return
      }

      analysisText =
        alert?.analysis_summary ||
        alert?.generated_analysis ||
        proposal?.aiOverview ||
        proposal?.analysis ||
        alert?.description ||
        proposal?.description ||
        ""

      title = alert?.title || proposal?.title || proposal?.external_id || "Esta proposta"

      const res = await fetch("/api/viral/generate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          analysisText,
          title,
          tone,
          audience: targetAudience,
          contentType,
        }),
      })

      const data = await res.json()
      let script = data?.script || ""
      script +=
        "\n\nQual sua opinião sobre isso ?\n1 - Gostei muito\n2- mais gostei do que não gostei\n3 - neutro\n4 - mais não gostei do que gostei\n5 - não gostei"
      setGeneratedScript(script)

      setTimeout(() => {
        generateAudioFromScript(script)
      }, 500)
    } catch (e) {
      const short = (text: string, n = 250) => text.replace(/\s+/g, " ").trim().slice(0, n)
      const summary = short(analysisText || `${title} — verifique os detalhes na Sentinela Vox.`, 240)
      let fallback = `🔎 ${title}\n\n${summary}\n\nFonte: Sentinela Vox.`
      fallback +=
        "\n\nQual sua opinião sobre isso ?\n1 - Gostei \n2- Mais gostei do que não gostei\n3 - Neutro\n4 - Mais não gostei do que gostei\n5 - Não gostei"
      setGeneratedScript(fallback)
    } finally {
      setIsGenerating(false)
    }
  }

  const saveViralContent = async () => {
    if (!generatedScript) return

    const supabase = createClient()
    let alertIdToUse = alert?.id ?? null

    if (!alertIdToUse) {
      if (!proposal) return

      const alertInsert = {
        proposal_id: proposal.id,
        title: proposal.title ?? `Alerta gerado para ${proposal.external_id ?? proposal.id}`,
        description: generatedScript || proposal.description || "",
        risk_level: "low",
      }

      const { data: insertedAlert, error: alertError } = await supabase
        .from("risk_alerts")
        .insert(alertInsert)
        .select()
        .single()
      if (alertError || !insertedAlert) {
        setIsSaving(false)
        return
      }
      alertIdToUse = insertedAlert.id
    }

    setIsSaving(true)
    const { error } = await supabase.from("viral_content").insert({
      alert_id: alertIdToUse,
      content_type: contentType,
      script: generatedScript,
      views: 0,
      shares: 0,
    })

    if (!error) {
      router.push(`/alert/${alertIdToUse}`)
    }
    setIsSaving(false)
  }

  const copyToClipboard = () => {
    navigator.clipboard.writeText(generatedScript)
  }

  const generateAudioFromScript = async (scriptText?: string) => {
    const textToConvert = scriptText || generatedScript
    if (!textToConvert) return
    setIsGeneratingAudio(true)
    try {
      const res = await fetch("/api/tts/generate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          script: textToConvert,
          voiceId: "33B4UnXyTNbgLmdEDh5P",
          model_id: "eleven_multilingual_v2",
        }),
      })

      const contentType = (res.headers.get("content-type") || "").toLowerCase()
      let blob: Blob | null = null

      if (contentType.includes("application/json")) {
        const dataJson = await res.json()
        if (dataJson?.audio) {
          if (typeof dataJson.audio === "string") {
            try {
              const bin = Uint8Array.from(atob(dataJson.audio), (c) => c.charCodeAt(0))
              blob = new Blob([bin], { type: dataJson.mime || "audio/mpeg" })
            } catch (err) { }
          } else if (Array.isArray(dataJson.audio)) {
            try {
              const uint = new Uint8Array(dataJson.audio)
              blob = new Blob([uint], { type: dataJson.mime || "audio/mpeg" })
            } catch (err) { }
          }
        }
      } else if (contentType.startsWith("audio/") || contentType === "application/octet-stream") {
        const arrayBuffer = await res.arrayBuffer()
        blob = new Blob([arrayBuffer], { type: contentType || "audio/mpeg" })
      }

      if (blob) {
        if (audioUrlRef.current) {
          try {
            URL.revokeObjectURL(audioUrlRef.current)
          } catch { }
          audioUrlRef.current = null
        }
        const url = URL.createObjectURL(blob)
        audioUrlRef.current = url
        setAudioUrl(url)
        setTimeout(() => {
          audioContainerRef.current?.scrollIntoView({ behavior: "smooth", block: "center" })
          audioRef.current?.play().catch(() => { })
        }, 150)
      }
    } catch (e) {
      console.error("Erro ao gerar TTS:", e)
    } finally {
      setIsGeneratingAudio(false)
    }
  }

  const downloadAudio = () => {
    if (!audioUrl) return
    const a = document.createElement("a")
    a.href = audioUrl
    a.download = `alert_audio_${proposal?.id ?? alert?.id ?? "script"}.mp3`
    document.body.appendChild(a)
    a.click()
    a.remove()
  }

  const transmitAudio = async () => {
    if (!audioUrl) return
    setIsTransmitting(true)
    try {
      const res = await fetch(audioUrl)
      const blob = await res.blob()

      const b64 = await new Promise<string>((resolve) => {
        const reader = new FileReader()
        reader.onloadend = () => {
          const result = reader.result as string
          resolve(result.split(",")[1])
        }
        reader.readAsDataURL(blob)
      })

      await fetch("/api/tts/transmit", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ audio: b64, mime: "audio/mpeg" }),
      })
    } catch (e) {
      console.error("transmit error", e)
    } finally {
      setIsTransmitting(false)
    }
  }

  const sendToWhatsapp = async () => {
    if (!generatedScript && !audioUrl) return
    setIsSendingWhatsapp(true)

    try {
      let audioBase64 = null
      const isNewsletter = phoneNumber.includes("@newsletter")

      if (audioUrl && !isNewsletter) {
        const res = await fetch(audioUrl)
        const blob = await res.blob()
        audioBase64 = await new Promise<string>((resolve) => {
          const reader = new FileReader()
          reader.onloadend = () => {
            resolve(reader.result as string)
          }
          reader.readAsDataURL(blob)
        })
      }

      let textToSend = generatedScript
      if (isNewsletter && audioUrl) {
        textToSend += `\n\n🎧 Áudio disponível em: ${window.location.origin}/audio-download\n\n⚠️ Limitação técnica: WhatsApp Channels API não suporta áudio direto. O áudio está disponível para download no link acima.`
      }

      const res = await fetch("/api/whatsapp/send", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          text: textToSend,
          audio: audioBase64,
          phone: phoneNumber,
          mime: "audio/mpeg",
          poll: sendPoll
            ? {
              question: pollQuestion,
              options: pollOptions.filter((o) => o.trim() !== "").map((o) => ({ name: o })),
            }
            : undefined,
        }),
      })

      const data = await res.json()

      if (res.ok) {
        if (isNewsletter && audioUrl) {
          window.alert("✅ Texto enviado para o Canal!\n\n⚠️ Áudio não enviado: WhatsApp Channels API tem limitações.")
        } else {
          window.alert("Enviado para o WhatsApp com sucesso!")
        }
      } else {
        window.alert(`Erro ao enviar: ${data.error || "Erro desconhecido"}`)
      }
    } catch (e) {
      window.alert("Erro ao conectar com o servidor.")
    } finally {
      setIsSendingWhatsapp(false)
    }
  }

  return (
    <div className="min-h-screen w-full relative overflow-hidden bg-background">
      {/* Background with blur effect */}
      <div className="absolute inset-0 z-0 pointer-events-none">
        <div
          className="absolute inset-0 bg-cover bg-center opacity-20"
          style={{
            backgroundImage:
              'url("https://www12.senado.leg.br/noticias/materias/2025/01/31/camara-tambem-tera-eleicao-em-1o-de-fevereiro/20150122_00159.jpg/mural/imagem_materia")',
            filter: "blur(8px)",
          }}
        />
        <div className="absolute inset-0 bg-gradient-to-br from-background/80 via-background/70 to-background/80" />
        <div className="absolute inset-0 backdrop-blur-sm" />
      </div>

      <header className="relative z-10 border-b border-border bg-card/50 backdrop-blur-sm">
        <div className="container mx-auto px-4 py-4">
          <div className="flex items-center justify-between">
            <Link href="/" className="flex items-center gap-2">
              <Shield className="h-8 w-8 text-primary" />
              <span className="text-2xl font-bold">MaracutaIA</span>
            </Link>
            <nav className="flex items-center gap-4">
              <Button variant="ghost" asChild>
                <Link href="/viral">Voltar</Link>
              </Button>
            </nav>
          </div>
        </div>
      </header>

      <main className="relative z-10 container mx-auto px-4 py-8">
        <div className="w-full max-w-[1600px] mx-auto">
          <div className="mb-8">
            <h1 className="text-3xl font-bold mb-2">Criar Conteúdo Viral</h1>
            <p className="text-muted-foreground">Configure e gere seu alerta viral em segundos</p>
          </div>

          <div className="grid lg:grid-cols-2 gap-6">
            {/* Coluna Esquerda: Configurações */}
            <div className="space-y-6">
              <Card className="bg-card/50 backdrop-blur-sm">
                <CardHeader>
                  <CardTitle className="text-lg">Criando alerta para</CardTitle>
                  <CardDescription>Proposta relacionada ao alerta selecionado</CardDescription>
                </CardHeader>
                <CardContent>
                  {alert || proposal ? (
                    <div className="flex items-center justify-between gap-4">
                      <div className="flex-1">
                        <div className="flex items-center gap-2 mb-2">
                          <Badge variant="outline" className="font-mono">
                            {alert?.legislative_proposals?.external_id ??
                              alert?.proposal_external_id ??
                              proposal?.external_id ??
                              "—"}
                          </Badge>
                          <Badge variant="secondary" className="text-xs">
                            {alert?.legislative_propostas || proposal ? "Proposta vinculada" : "Sem vínculo"}
                          </Badge>
                        </div>
                        <h3 className="font-semibold">
                          {alert?.legislative_proposals?.title ??
                            alert?.title ??
                            proposal?.title ??
                            "Título não disponível"}
                        </h3>
                      </div>
                      <div className="flex-shrink-0">
                        <Link
                          href={`/proposal/${alert?.proposal_id ?? proposal?.id ?? ""}`}
                          className="inline-block text-sm text-primary underline"
                        >
                          Ver proposta
                        </Link>
                      </div>
                    </div>
                  ) : (
                    <div className="flex items-center justify-center py-4 text-muted-foreground">
                      <Loader2 className="h-5 w-5 animate-spin mr-2" />
                      Carregando informações do alerta...
                    </div>
                  )}
                </CardContent>
              </Card>

              <Card className="bg-card/50 backdrop-blur-sm">
                <CardHeader>
                  <CardTitle>Configurações</CardTitle>
                  <CardDescription>Personalize o tom e o público-alvo</CardDescription>
                </CardHeader>
                <CardContent className="space-y-6">
                  <div>
                    <Label className="mb-3 block">Tipo de Conteúdo</Label>
                    <div className="flex">
                      <div className="flex gap-3 mr-1">
                        <Badge variant="default" className="cursor-pointer">
                          <Volume2 className="mr-1 h-3 w-3" />
                          Áudio
                        </Badge>
                      </div>
                      <div className="flex gap-3">
                        <Badge variant="default" className="cursor-pointer">
                          <MessageSquare className="mr-1 h-3 w-3" />
                          Mensagem
                        </Badge>
                      </div>
                    </div>
                  </div>

                  <div className="space-y-4 pt-4 border-t border-border">
                    <div className="flex items-center justify-between">
                      <Label className="text-base font-semibold flex items-center gap-2">
                        <List className="h-4 w-4" />
                        Enquete do WhatsApp
                      </Label>
                      <div className="flex items-center gap-2">
                        <input
                          type="checkbox"
                          id="sendPoll"
                          checked={sendPoll}
                          onChange={(e) => setSendPoll(e.target.checked)}
                          className="h-4 w-4 rounded border-primary text-primary focus:ring-primary"
                        />
                        <Label htmlFor="sendPoll" className="cursor-pointer">
                          Incluir
                        </Label>
                      </div>
                    </div>

                    {sendPoll && (
                      <div className="space-y-3 pl-2 border-l-2 border-primary/20">
                        <div>
                          <Label className="text-xs text-muted-foreground mb-1 block">Pergunta</Label>
                          <Input
                            value={pollQuestion}
                            onChange={(e) => setPollQuestion(e.target.value)}
                            placeholder="Digite a pergunta da enquete"
                            className="bg-background/50"
                          />
                        </div>
                        <div>
                          <Label className="text-xs text-muted-foreground mb-1 block">Opções</Label>
                          <div className="space-y-2">
                            {pollOptions.map((option, index) => (
                              <div key={index} className="flex gap-2">
                                <Input
                                  value={option}
                                  onChange={(e) => {
                                    const newOptions = [...pollOptions]
                                    newOptions[index] = e.target.value
                                    setPollOptions(newOptions)
                                  }}
                                  placeholder={`Opção ${index + 1}`}
                                  className="bg-background/50"
                                />
                                {pollOptions.length > 2 && (
                                  <Button
                                    variant="ghost"
                                    size="icon"
                                    onClick={() => {
                                      const newOptions = pollOptions.filter((_, i) => i !== index)
                                      setPollOptions(newOptions)
                                    }}
                                    className="h-9 w-9 text-muted-foreground hover:text-destructive"
                                  >
                                    <Trash2 className="h-4 w-4" />
                                  </Button>
                                )}
                              </div>
                            ))}
                          </div>
                          {pollOptions.length < 12 && (
                            <Button
                              variant="outline"
                              size="sm"
                              onClick={() => setPollOptions([...pollOptions, ""])}
                              className="mt-2 w-full border-dashed"
                            >
                              <Plus className="mr-2 h-3 w-3" /> Adicionar Opção
                            </Button>
                          )}
                        </div>
                      </div>
                    )}
                  </div>

                  <Button
                    onClick={generateScript}
                    disabled={isGenerating || isGeneratingAudio || (!alert && !proposal && !(source && originId))}
                    className="w-full"
                    size="lg"
                  >
                    {isGenerating ? (
                      <>
                        <Wand2 className="mr-2 h-4 w-4 animate-spin" />
                        Gerando...
                      </>
                    ) : (
                      <>
                        <Sparkles className="mr-2 h-4 w-4" />
                        Gerar Script Viral
                      </>
                    )}
                  </Button>
                </CardContent>
              </Card>
            </div>

            {/* Coluna Direita: Resultado (Loading ou Conteúdo) */}
            <div className="space-y-6">

              {(isGenerating || isGeneratingAudio) && (
                <Card className="bg-card/50 backdrop-blur-sm border-primary/20 h-full flex items-center justify-center min-h-[400px]">
                  <CardContent className="flex flex-col items-center gap-6 p-8 text-center">
                    <div className="relative">
                      <div className="absolute inset-0 bg-primary/20 blur-xl rounded-full animate-pulse" />
                      <div className="relative bg-background p-4 rounded-full border border-primary/20 shadow-lg">
                        {isGenerating ? (
                          <BrainCircuit className="h-12 w-12 text-primary animate-pulse" />
                        ) : (
                          <Mic className="h-12 w-12 text-primary animate-bounce" />
                        )}
                      </div>
                    </div>

                    <div className="space-y-2">
                      <h3 className="text-xl font-bold">
                        {isGenerating ? "Analisando Proposta..." : "Sintetizando Voz Neural..."}
                      </h3>
                      <p className="text-muted-foreground max-w-xs mx-auto">
                        {isGenerating
                          ? "Nossa IA está lendo o texto da lei e criando um roteiro otimizado para viralização."
                          : "Transformando o roteiro em um áudio natural e engajador para compartilhamento."}
                      </p>
                    </div>

                    <div className="flex gap-2 mt-4">
                      <div
                        className={`h-2 w-2 rounded-full ${isGenerating ? "bg-primary animate-bounce" : "bg-primary/30"}`}
                        style={{ animationDelay: "0s" }}
                      />
                      <div
                        className={`h-2 w-2 rounded-full ${isGenerating ? "bg-primary animate-bounce" : "bg-primary/30"}`}
                        style={{ animationDelay: "0.2s" }}
                      />
                      <div
                        className={`h-2 w-2 rounded-full ${isGenerating ? "bg-primary animate-bounce" : "bg-primary/30"}`}
                        style={{ animationDelay: "0.4s" }}
                      />
                    </div>
                  </CardContent>
                </Card>
              )}

              {!isGenerating && !isGeneratingAudio && generatedScript && (
                <Card className="bg-card/50 backdrop-blur-sm">
                  <CardHeader>
                    <CardTitle>Conteúdo Gerado</CardTitle>
                    <CardDescription>Revise o script e ouça o áudio antes de compartilhar</CardDescription>
                  </CardHeader>
                  <CardContent className="space-y-4">
                    <Textarea
                      value={generatedScript}
                      onChange={(e) => setGeneratedScript(e.target.value)}
                      rows={12}
                      className="font-mono text-sm bg-background/50"
                    />
                    <div className="flex gap-2">
                      <Button variant="outline" onClick={copyToClipboard} className="flex-1 bg-transparent">
                        <Copy className="mr-2 h-4 w-4" />
                        Copiar Texto
                      </Button>
                      <Button onClick={saveViralContent} disabled={isSaving} className="flex-1">
                        {isSaving ? "Salvando..." : "Salvar no Histórico"}
                      </Button>
                    </div>

                    {audioUrl && (
                      <div ref={audioContainerRef} className="mt-6 space-y-4">
                        <div className="p-4 border border-border rounded-lg flex flex-col sm:flex-row items-center gap-4 bg-background/50">
                          <div className="h-10 w-10 rounded-full bg-primary/10 flex items-center justify-center shrink-0">
                            <Volume2 className="h-5 w-5 text-primary" />
                          </div>
                          <audio ref={audioRef} src={audioUrl} controls className="flex-1 w-full" />
                          <div className="flex gap-2 w-full sm:w-auto">
                            <Button
                              variant="outline"
                              onClick={downloadAudio}
                              className="flex-1 sm:flex-none bg-transparent"
                            >
                              Baixar
                            </Button>
                            <Button onClick={transmitAudio} disabled={isTransmitting} className="flex-1 sm:flex-none">
                              Transmitir
                            </Button>
                          </div>
                        </div>

                        <div className="p-4 border border-border rounded-lg bg-muted/30 space-y-4">
                          <h4 className="font-medium text-sm flex items-center gap-2">
                            <MessageSquare className="h-4 w-4" />
                            Compartilhar no WhatsApp
                          </h4>

                          {/* Channel Selector */}
                          <div className="space-y-4">
                            {/* CANAIS */}
                            <div className="border rounded-md p-3 bg-background/50">
                              <div
                                className="flex items-center justify-between cursor-pointer"
                                onClick={() => setIsChannelsOpen(!isChannelsOpen)}
                              >
                                <div className="flex items-center gap-2">
                                  <span className="font-medium text-sm">Canais do WhatsApp</span>
                                  {selectedChannelName && !isChannelsOpen && (
                                    <Badge variant="secondary" className="text-[10px] flex items-center gap-1">
                                      <Check className="h-3 w-3" /> {selectedChannelName}
                                    </Badge>
                                  )}
                                </div>
                                {isChannelsOpen ? (
                                  <ChevronUp className="h-4 w-4 text-muted-foreground" />
                                ) : (
                                  <ChevronDown className="h-4 w-4 text-muted-foreground" />
                                )}
                              </div>

                              {isChannelsOpen && (
                                <div className="mt-3 space-y-2">
                                  <Button
                                    variant="outline"
                                    size="sm"
                                    className="w-full text-xs justify-start bg-transparent"
                                    onClick={async (e) => {
                                      e.stopPropagation()
                                      setIsLoadingChannels(true)
                                      try {
                                        const res = await fetch("/api/whatsapp/channel/list")
                                        const data = await res.json()
                                        if (Array.isArray(data)) {
                                          setChannels(data)
                                        } else if (data.value && Array.isArray(data.value)) {
                                          setChannels(data.value)
                                        } else {
                                          window.alert("Nenhum canal encontrado.")
                                        }
                                      } catch (e) {
                                        window.alert("Erro ao carregar canais.")
                                      } finally {
                                        setIsLoadingChannels(false)
                                      }
                                    }}
                                  >
                                    {isLoadingChannels
                                      ? "Carregando..."
                                      : channels.length > 0
                                        ? "Atualizar lista"
                                        : "Carregar meus canais"}
                                  </Button>

                                  {channels.length > 0 && (
                                    <div className="grid gap-2 max-h-60 overflow-y-auto p-1">
                                      {channels.map((ch: any, index: number) => (
                                        <div
                                          key={ch.id || index}
                                          className={`flex items-center justify-between p-2 rounded cursor-pointer text-xs border ${phoneNumber === ch.id ? "bg-primary/10 border-primary" : "hover:bg-accent border-transparent"}`}
                                          onClick={() => {
                                            setPhoneNumber(ch.id || "")
                                            setSelectedChannelName(ch.name || "Canal sem nome")
                                            setSelectedGroupName("")
                                            setIsChannelsOpen(false)
                                          }}
                                        >
                                          <div className="flex items-center gap-2">
                                            {ch.picture && (
                                              <img
                                                src={ch.picture || "/placeholder.svg"}
                                                alt=""
                                                className="w-6 h-6 rounded-full"
                                              />
                                            )}
                                            <span className="font-medium">{ch.name || "Sem nome"}</span>
                                          </div>
                                          {phoneNumber === ch.id && <Check className="h-3 w-3 text-primary" />}
                                        </div>
                                      ))}
                                    </div>
                                  )}
                                </div>
                              )}
                            </div>

                            {/* GRUPOS */}
                            <div className="border rounded-md p-3 bg-background/50">
                              <div
                                className="flex items-center justify-between cursor-pointer"
                                onClick={() => setIsGroupsOpen(!isGroupsOpen)}
                              >
                                <div className="flex items-center gap-2">
                                  <span className="font-medium text-sm">Grupos do WhatsApp</span>
                                  {selectedGroupName && !isGroupsOpen && (
                                    <Badge variant="secondary" className="text-[10px] flex items-center gap-1">
                                      <Check className="h-3 w-3" /> {selectedGroupName}
                                    </Badge>
                                  )}
                                </div>
                                {isGroupsOpen ? (
                                  <ChevronUp className="h-4 w-4 text-muted-foreground" />
                                ) : (
                                  <ChevronDown className="h-4 w-4 text-muted-foreground" />
                                )}
                              </div>

                              {isGroupsOpen && (
                                <div className="mt-3 space-y-2">
                                  <Button
                                    variant="outline"
                                    size="sm"
                                    className="w-full text-xs justify-start bg-transparent"
                                    onClick={async (e) => {
                                      e.stopPropagation()
                                      setIsLoadingGroups(true)
                                      try {
                                        const res = await fetch("/api/whatsapp/groups/list")
                                        const data = await res.json()
                                        if (Array.isArray(data)) {
                                          setGroups(data)
                                        } else if (data.value && Array.isArray(data.value)) {
                                          setGroups(data.value)
                                        } else {
                                          window.alert("Nenhum grupo encontrado.")
                                        }
                                      } catch (e) {
                                        window.alert("Erro ao carregar grupos.")
                                      } finally {
                                        setIsLoadingGroups(false)
                                      }
                                    }}
                                  >
                                    {isLoadingGroups
                                      ? "Carregando..."
                                      : groups.length > 0
                                        ? "Atualizar lista"
                                        : "Carregar meus grupos"}
                                  </Button>

                                  {groups.length > 0 && (
                                    <div className="grid gap-2 max-h-60 overflow-y-auto p-1">
                                      {groups.map((grp: any, index: number) => (
                                        <div
                                          key={grp.id || index}
                                          className={`flex items-center justify-between p-2 rounded cursor-pointer text-xs border ${phoneNumber === grp.id ? "bg-primary/10 border-primary" : "hover:bg-accent border-transparent"}`}
                                          onClick={() => {
                                            const id = grp.id || grp.phone || ""
                                            if (id) {
                                              setPhoneNumber(id)
                                              setSelectedGroupName(grp.name || grp.subject || "Grupo sem nome")
                                              setSelectedChannelName("")
                                              setIsGroupsOpen(false)
                                            }
                                          }}
                                        >
                                          <div className="flex items-center gap-2">
                                            {grp.picture && (
                                              <img
                                                src={grp.picture || "/placeholder.svg"}
                                                alt=""
                                                className="w-6 h-6 rounded-full"
                                              />
                                            )}
                                            <span className="font-medium">{grp.name || grp.subject || "Sem nome"}</span>
                                          </div>
                                          {phoneNumber === grp.id && <Check className="h-3 w-3 text-primary" />}
                                        </div>
                                      ))}
                                    </div>
                                  )}
                                </div>
                              )}
                            </div>
                          </div>

                          <div className="flex gap-2">
                            <input
                              type="text"
                              placeholder="5511999999999 ou ID do canal"
                              value={phoneNumber || ""}
                              onChange={(e) => setPhoneNumber(e.target.value)}
                              className="flex-1 px-3 py-2 text-sm rounded-md border border-input bg-background"
                            />
                            <Button onClick={sendToWhatsapp} disabled={isSendingWhatsapp}>
                              {isSendingWhatsapp ? "Enviando..." : "Enviar"}
                            </Button>
                          </div>

                          <div className="flex justify-end">
                            <Button
                              variant="link"
                              size="sm"
                              className="text-xs h-auto p-0 text-muted-foreground hover:text-primary"
                              onClick={async () => {
                                const defaultName = alert?.title || proposal?.title || "Novo Canal"
                                const name = window.prompt("Nome do novo canal:", defaultName)
                                if (!name) return

                                try {
                                  const res = await fetch("/api/whatsapp/channel/create", {
                                    method: "POST",
                                    headers: { "Content-Type": "application/json" },
                                    body: JSON.stringify({ name }),
                                  })
                                  const data = await res.json()
                                  const newId = data.value?.id || data.id || data.newsletterId

                                  if (newId) {
                                    setPhoneNumber(newId)
                                    window.alert(`Canal "${name}" criado! ID preenchido.`)
                                  } else {
                                    window.alert("Canal criado, mas não foi possível obter o ID automaticamente.")
                                  }
                                } catch (e) {
                                  window.alert("Erro ao criar canal.")
                                }
                              }}
                            >
                              + Criar novo canal automaticamente
                            </Button>
                          </div>
                        </div>
                      </div>
                    )}
                  </CardContent>
                </Card>
              )}
            </div>
          </div>
        </div>
      </main>
    </div>
  )
}
